Privacy policy
UniSynTechnologies/policy-generator pull request #1
Opened 2018-06-24 00:41 UTC by NoahMcGraw

Privacy Policy generates a custom privacy policy for it's user using common clauses and allows for custom clauses to be added.
Phase 1: Established a general format for the app. Also developed the starting page and question 1 for the questionnaire.

2018-06-25 02:57 UTC, reesemartin requested changes
You have a lot of stuff in the controller that should be in partials. You should keep the controller just manipulating the data and put all that text in a partial.
You should create directives to split all that up that way you arent mixing visual stuff with the controller and so that your index.php doesnt become this super long file.

Should do something like:
```
<policy-initial-info ng-show="newPolicy.addingInfo"></policy-initial-info>
<policy-questionaire ng-show="newPolicy.questionaire"></policy-questionaire>
```
And then inside those call sub directives for each page in the questionaire.


Doing directives will also make it easier to just drop this into a wordpress plugin format instead of an html file like it is. So create a directive for the app as a whole even above the initial info and questionaire.


Also all your inputs with validation like required need ng-messages.
```
<div ng-messages="initialInfoForm.companyName.$error">
    <div ng-message="required"><span class="error">This field is required.</span></div>
</div>
```


Remove the unisyn footer module

2018-06-29 18:52 UTC, reesemartin requested changes
All the templates should be html files not php files. There could be some neat server interaction using php files as templates. I didnt know you could do that and it work. But this will not need it so change them to html and the template urls in directives please.

2018-06-29 18:52 UTC, reesemartin commented on app/controllers/main-ctrl.js
> +    $scope.questionnaire = {
What does this object do? I was thinking it was unlikely you should be doing "false" instead of the boolean false so I looked for where its being used and cant find anything.

2018-06-29 18:52 UTC, reesemartin commented on app/directives/policyQuestionnaire.js
> +        controller: 'mainCtrl',
Not necessary since this directive does not create a child scope, it just uses whatever the parent is using which is already mainCtrl

2018-06-29 18:52 UTC, reesemartin commented on app/directives/questionnaireTabs/questionnaireSharing.js
> +        controller: 'mainCtrl',
Not necessary since this directive does not create a child scope, it just uses whatever the parent is using which is already mainCtrl

2018-06-29 18:52 UTC, reesemartin commented on app/directives/questionnaireTabs/questionnaireStorage.js
> +        controller: 'mainCtrl',
Not necessary since this directive does not create a child scope, it just uses whatever the parent is using which is already mainCtrl

2018-06-29 18:52 UTC, reesemartin commented on app/directives/questionnaireTabs/questionnaireUsage.js
> +        controller: 'mainCtrl',
Not necessary since this directive does not create a child scope, it just uses whatever the parent is using which is already mainCtrl

2018-06-29 18:52 UTC, reesemartin commented on app/partials/policyQuestionnaire-template.php
> +    <md-button class="md-primary md-raised">
I think it would help the UX if you added a css rule like this:
```
.unisyn-big-button.md-button {
    width: 100%;
    padding-top: 10px;
    padding-bottom: 10px;
    margin-left: 0;
    margin-right: 0;
    font-size: 16px;
}
```
Then use class unisyn-big-button on this button to make it more obvious down there.

2018-06-29 18:52 UTC, reesemartin commented on app/partials/policyQuestionnaire-template.php
> +    <md-button class="md-accent" ng-click="backToInitialInfo()">Edit Company Info</md-button>
Might be nice to move this to the top right of the toolbar in the questionaire tabs and remove the md-accent so its just white text in the toolbar like this:
![image](https://user-images.githubusercontent.com/19984334/42108835-447eddb2-7ba1-11e8-82e7-c38788e87b8d.png)

2018-06-29 18:52 UTC, reesemartin commented on app/partials/questionnaireTabs/questionnaireSharing-template.php
> +        <div class="md-toolbar-tools" style="text-align: center;">
Remove the text-align: center here once you have added the edit company info button to the toolbar.

2018-06-29 18:52 UTC, reesemartin commented on app/partials/privacyPolicyGenerator-template.php
> +            <md-button class="md-primary md-raised" ng-click="startNewPolicy()" ng-hide="newPolicy.addingInfo || newPolicy.questionaire">Let's Get Started</md-button>
Same as the generate policy button, I think it would help the UX if you added a css rule like this:
```
.unisyn-big-button.md-button {
    width: 100%;
    padding-top: 10px;
    padding-bottom: 10px;
    margin-left: 0;
    margin-right: 0;
    font-size: 16px;
}
```
Then use class unisyn-big-button on this button

2018-06-29 18:52 UTC, reesemartin commented on index.php
> +        <script src="/app/controllers/policyQuestionnaire-ctrl.js"></script>
This file is a 404 so remove the link

2018-06-29 18:52 UTC, reesemartin commented on app/partials/policyQuestionnaire-template.php
> +    <md-tabs md-dynamic-height="true">
I suggest using
```
md-selected="newPolicy.selectedTab"
```
here to also be able to programatically change tabs.

In your controller add that property to newPolicy at the top and initialize it as 0. It works like an array with 0 being first tab 1 being second.

2018-06-29 18:52 UTC, reesemartin commented on app/partials/policyQuestionnaire-template.php
> +    </md-tabs>
I would add a button above generate policy for "Next" that increments newPolicy.selectedTab by 1. If newPolicy.selectedTab equals 2 then it is on the last tab so hide the button.

No real need for a back button since they can click tabs at top to go back.

I would apply md-accent and md-raised and the unisyn-big-button classes.

This isnt required but I think it would help. If they messed up or want to review something they can break the flow by scrolling up and selecting a tab to review or clicking edit company info. Otherwise they would fill out the info moving down and then click next or generate.

2018-06-30 01:59 UTC, NoahMcGraw commented on app/controllers/main-ctrl.js
> +    $scope.questionnaire = {
This object holds the results from each questionnaire tab. The answer key is being used as a model in the md-radio-group at the bottom of each tab. As far as I have been able to tell, the value passed in md-radio is always passed as a string. I was having issues with getting the value to bind to the ctrl as a bool true or false but I think it has everything to do with me using "value" instead of "ng-value". Will test and follow up on that.

2018-06-30 02:07 UTC, NoahMcGraw commented on app/controllers/main-ctrl.js
> +    $scope.questionnaire = {
Yep that's what it was. I've made the changes to reflect that logic in the ctrl and partial

2018-06-30 06:50 UTC, reesemartin requested changes

2018-06-30 06:50 UTC, reesemartin commented on index.php
> +        <link href="/app/modules/angular-material/1.1.5/angular-material.min.css" type="text/css" rel="stylesheet">
Add material icons stylesheet here to gain access to them in the app
```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```

2018-06-30 06:50 UTC, reesemartin commented on app/partials/questionnaireTabs/questionnaireUsage-template.html
> +                        <md-icon md-svg-src="/app/assets/images/icons/close-24px.svg">
Use material-icons font set to call the material icon
```
<md-icon md-font-set="material-icons"> close </md-icon>
```

2018-06-30 06:50 UTC, reesemartin commented on app/assets/images/icons/close-24px.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
Delete this file

2018-06-30 06:50 UTC, reesemartin commented on app/assets/images/icons/help-24px.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
Delete this file

2018-06-30 06:50 UTC, reesemartin commented on app/partials/questionnaireTabs/questionnaireUsage-template.html
> +        <md-icon md-svg-src="/app/assets/images/icons/help-24px.svg">
Use material-icons font set to call the material icon
```
<md-icon md-font-set="material-icons"> help </md-icon>
```

2018-07-01 03:05 UTC, merged